name: qiuwenlong
age: 18
password: 6874
header: '{cipher}6cb4958e96ac73ace0c8690018bfc6493b177005acb1813b5795761c8b97bf37'
spring:
  datasource:
    jdbc-url: jdbc:mysql://192.168.1.7:3306/test?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Abc@1234%