name: qiuwenlong
age: 18
password: 6874
header: '{cipher}2ba069c635d90ea592a44fc457a84304068c85eef5bb0c202e4ff805890c1eb2'
spring:
  datasource:
    jdbc-url: jdbc:mysql://192.168.1.20:3306/test?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Abc@1234%